# Generated by Django 5.1.7 on 2025-03-10 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'preparing'), ('SHIPPING', 'shipping'), ('COMPLETED', 'completed'), ('CANCEL', 'cancel')], default='PREPARING', max_length=20),
        ),
    ]
